### ISSUE TITLE
webd更新新版本（6月4）编译固件出错

### ISSUE THREAD

**Issue by kwy-hu** [Hyy2001X/AutoBuild-Actions-BETA#24]
这两天编译自定义固件后出错，不加入webd后能顺利编译。刚查看了webd6月4号更新了。烦请老大更新下，以便继续可编译。谢谢

**Comment by LIKE2000-ART** [comment]
[[https://github.com/Hyy2001X/AutoBuild-Actions-BETA/issues/23](url)](https://github.com/LIKE2000-ART/AutoBuild-Packages)

我自己修改了一版，目前webd可用
