### ISSUE TITLE
希望能提供带clash_meta内核的版本

### ISSUE THREAD

**Issue by spysoos** [Hyy2001X/AutoBuild-Actions-BETA#29]
希望能提供带clash_meta内核的版本，不知道Newifi 3够不够装

**Comment by Soupure** [comment]
下载meta内核直接失败了

**Comment by Hyy2001X** [comment]
> 下载meta内核直接失败了

可以fork仓库自己编译的，需要提供帮助可以提交issue

**Comment by Soupure** [comment]
应该是空间不够。小白不知道怎么编译meta内核进去www

**Comment by Hyy2001X** [comment]
> 应该是空间不够。小白不知道怎么编译meta内核进去www

新三的话，Fork 我的仓库就可以编译了，[这行](https://github.com/Hyy2001X/AutoBuild-Actions-BETA/blob/8da151cf7ccab864bdb1124fe9c27ff33af81fda/Scripts/AutoBuild_DiyScript.sh#L93)改为`ClashDL mipsle-hardfloat meta`
