### ISSUE TITLE
AX6S随机重启问题

### ISSUE THREAD

**Issue by molehzy** [Hyy2001X/AutoBuild-Actions-BETA#5]
从包含Natter的版本开始，只要PPPoE拨号成功就会不定时重启，有时几分钟重启一次，有时几小时重启一次，换回老版本就没有这个问题

**Comment by Hyy2001X** [comment]
我这个AX6S是DHCP上网的，还没遇到过随机重启的情况，PPPoE的话我这边暂时没有条件来测试测试

**Comment by molehzy** [comment]
我试试其他新版本固件看看
