### ISSUE TITLE
新版在线升级sha256检验失败

### ISSUE THREAD

**Issue by ilxp** [Hyy2001X/AutoBuild-Actions-BETA#51]
发在：https://github.com/Hyy2001X/AutoBuild-Actions-BETA/issues/50 
我自己本地sha256值是没有问题的，就6.10版本出问题，换回6.9.12版本，sha值校验没有问题，麻烦大佬再看看。

还有个问题，脚本更新哪里，会出现乱码，6.10和6.9都有问题。

以上问题是在lean大佬的lede源码，luci18上 的。

**Comment by ilxp** [comment]
![1730209665052](https://github.com/user-attachments/assets/d32b6fba-3a41-4b16-b7ed-441ff17a6b51)

**Comment by ilxp** [comment]
我在lean的lede的luci18上发现问题是：1、v6.10sha256值检验失败，6.9.12则没有问题。2、检测脚本这里，云短版本版本号，出现乱码。
在openwrt最新master的luci上，v6.10sha256值校验成功，2脚本云端版本号没有出现乱码 但是有个问题，点击 执行更新  跳转到日志，出现网络连接错误。 lede的luci18上没有这个错误。
![1730210490885](https://github.com/user-attachments/assets/ece83510-e1f0-4950-b641-41f80f8009e3)
![1730210516461](https://github.com/user-attachments/assets/1370366a-e3ae-4ff3-bd3a-0b9c9add301d)
![1730210597097](https://github.com/user-attachments/assets/ba4dcaf7-f8de-46b5-a263-b4deab8fc72d)
![1730211110033](https://github.com/user-attachments/assets/146430f9-46a7-45e8-bfde-a92cc429e5dc)

**Comment by ilxp** [comment]
我在tmp目录下去看了，lede下没有下载到文件。所以sha256值失败。文件只有几k。

:03] 正在下载固件,请耐心等待 ...
error code: 1003error code: 1003error code: 1003error code: 1003
[22:51:08] 固件下载成功!
[22:51:08] SHA256 校验失败!

使用命令autoupdate -u --verbose 错误如下：
正在下载固件,请耐心等待 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8877    0  8877    0     0  12792      0 --:--:-- --:--:-- --:--:-- 12791
error code: 1003error code: 1003error code: 1003error code: 1003
[22:52:36] 固件下载成功!
[22:52:36] SHA256 校验失败!

**Comment by ilxp** [comment]
镜像是系统自动选择的hub.gitmirror.com。估计是这个问题。

**Comment by Hyy2001X** [comment]
> 镜像是系统自动选择的hub.gitmirror.com。估计是这个问题。

是的，这个镜像有小黄云防护，脚本更新后默认不使用这个镜像

**Comment by ilxp** [comment]
大佬，最新版6.10.1使用下来没有问题，非常好。但是luci-app-autoupdate这个还是有个bug没有得到解决。就是在js的luci上，点击执行更新，还是跳转到日志里，没有执行，显示网络连接错误，请稍后再试。空了看下。
